### ISSUE TITLE
New Error: Unable to simultaneously satisfy constraints.

### ISSUE THREAD

**Issue by sidan5** [preemptive/PPiOS-Rename#17] opened 2018-06-26 12:34 UTC
Seems that all constrains are somehow being mixed up on the obfuscated code. This is include programmed constrains and constrains that are on the xib files. Is there any solution for that?

**Comment by neuralmer** [comment] 2018-07-03 15:01
Typically, issues with *PPiOS-Rename* fall into one of a few categories:

1. XIB/Storyboards get out of synch. with the `symbols.map`, since *PPiOS-Rename* modifies the .xib files directly the changes must be reverted before rerunning obfuscation.
2. The `*-prefix.pch` doesn't exist or isn't being included correctly.
3. Identifier names are referenced indirectly (for example with [Key-Value Compliance / KVO](https://github.com/preemptive/PPiOS-Rename#key-value-observing-kvo)), and this indirect reference is not updated using the `#define` mechanism.

The first category is easy to solve, assuming you are using some sort of source control, you just need to make sure that any changes made to the .xib files by *PPiOS-Rename* have been reverted before running obfuscation again.

The second category is also pretty easy to fix with instructions [here](https://github.com/preemptive/PPiOS-Rename#missing-pch-file).  Given that you have looked at the closed issues, you are probably not running into either of these.

The third category can be easy to fix if the issue is one of the items discussed in the readme. This category can also be harder to fix if it isn't known how renamed entities are being referenced, but once that is figured out either the code can be changed to make the reference direct or to exclude that name with `-x` or `-F`.

A certain (although time consuming) way to figure out which renaming is causing the issue can be found by going through an iterative process:

1. Revert code changes from the last run of *PPiOS-Rename*.
2. Update the contents of `symbols.map`.
3. Obfuscate by running the `Apply Renaming to <original-target-name>` target.
4. Test the resulting binary.

Step 2 updates the `symbols.map` based on whether the test in step 4 from the prior iteration was successful. This allows a binary search of the renamings in `symbols.map` for the offending renaming, keeping in mind that more than one renaming may be causing a problem.

Once a problematic renaming is found, it should be relatively easy to figure out why it is causing a problem by looking at where that original name is used. This symbol can then be excluded when doing the analysis phase as described [here](https://github.com/preemptive/PPiOS-Rename#undefined-symbols--exclusions). Other symbols that are involved in similar indirect references can also be excluded.

With these suggestions, if you are still not able to fix your issue, I will need additional detail as to what exactly is going on to be able to help.

**Comment by sidan5** [comment] 2018-07-04 10:55
@neuralmer Thank you for this response however this is not the case. I figured how to solve it by changing some constraints on the obfuscated code but for you to solve globally I will try to add some sample code when I would have time.

**Comment by neuralmer** [comment] 2018-07-10 13:53
I am curious to know what is going on, even without sample code.

**Comment by neuralmer** [comment] 2018-09-24 13:47
Closing. Please reopen if and when additional details are available.

**Closed as completed by neuralmer** 2018-09-24 13:47 UTC
